
# 장바구니 조회 테스트
### 정상 케이스
GET http://localhost:8080/api/cart/items



# 장바구니 추가 테스트 
### 정상 케이스
POST http://localhost:8080/api/cart/items
Content-Type: application/json

{
  "productId": 1,
  "quantity": 1
}

### 존재하지 않는 상품 테스트, 400
POST http://localhost:8080/api/cart/items
Content-Type: application/json

{
  "productId": 999,
  "quantity": 1
}

### 수량 0 테스트, 400
POST http://localhost:8080/api/cart/items
Content-Type: application/json

{
  "productId": 1,
  "quantity": 0
}



# 장바구니 삭제 테스트
### 정상 케이스
DELETE http://localhost:8080/api/cart/items/5


### 장바구니 전체 삭제
DELETE http://localhost:8080/api/cart/items